# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Ubuntu 20.04.3 LTS - Focal Fossa
    config.vm.box = "ubuntu/focal64"

    config.vm.provider :virtualbox do |vb|
        vb.name = "postgresql-1"
        vb.memory = "2048"
        vb.gui = true
    end

    config.vm.network :forwarded_port, guest: 5432, host: 5432
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provision "shell", path: "root-login-enable.sh"
    config.vm.provision "shell", path: "install-postgresql.sh"
end