@startuml
'https://plantuml.com/class-diagram

abstract class PropertySource
abstract class EnumerablePropertySource
class MapPropertySource
class PropertiesPropertySource
class ResourcePropertySource
class CompositePropertySource
abstract class CommandLinePropertySource
class SimpleCommandLinePropertySource
class SystemEnvironmentPropertySource

interface PropertySources
class MutablePropertySources

interface PropertyResolver
interface Environment
interface ConfigurableEnvironment
abstract class AbstractEnvironment
class StandardEnvironment
class ApplicationEnvironment

interface ConfigurablePropertyResolver
abstract class AbstractPropertyResolver
class PropertySourcesPropertyResolver

PropertySource <|-- EnumerablePropertySource
EnumerablePropertySource <|-- MapPropertySource
MapPropertySource <|-- PropertiesPropertySource
MapPropertySource <|-- SystemEnvironmentPropertySource
PropertiesPropertySource <|-- ResourcePropertySource
EnumerablePropertySource <|-- CompositePropertySource
EnumerablePropertySource <|-- CommandLinePropertySource
CommandLinePropertySource <|-- SimpleCommandLinePropertySource

PropertySources <|.. MutablePropertySources

PropertyResolver <|.. Environment
Environment <|.. ConfigurableEnvironment
ConfigurableEnvironment <|.. AbstractEnvironment
AbstractEnvironment <|-- StandardEnvironment
StandardEnvironment <|-- ApplicationEnvironment

PropertyResolver <|-- ConfigurablePropertyResolver
ConfigurablePropertyResolver <|.. AbstractPropertyResolver
AbstractPropertyResolver <|-- PropertySourcesPropertyResolver

@enduml