spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:spring/spring-thymeleaf/src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:spring/spring-thymeleaf/src/main/resources/static/
#    cache-period: 0