---
- hosts: all
  name: Dev Kafka Vagrant Ansible Local
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Install packages
      apt:
        name: ['mc', 'default-jdk']
        update_cache: yes
        state: latest
        force_apt_get: yes

    - name: Create a Zoo Keeper directory
      file:
        path: /opt/zoo-keeper
        state: directory
        mode: 0755

    - name: Create a Zoo Keeper data directory
      file:
        path: /var/zoo-keeper/data
        state: directory
        mode: 0755

    - name: Download a zoo Keeper archive
      get_url:
        url: https://www2.apache.paket.ua/zookeeper/zookeeper-3.7.0/apache-zookeeper-3.7.0-bin.tar.gz
        dest: /opt/zoo-keeper
        mode: 0755

    - name: Unarchive a zoo Kepper
      unarchive:
        src: /opt/zoo-keeper/apache-zookeeper-3.7.0-bin.tar.gz
        dest: /opt/zoo-keeper/
        extra_opts: [ --strip-components=1 ]
        remote_src: yes