# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "zoo-keeper-1" do |d|
        d.vm.box = "ubuntu/bionic64"
        d.vm.network "public_network", ip: "192.168.1.33"
        d.vm.provider "virtualbox" do |v|
            v.name = "zoo-keeper-1"
            v.gui = true
            v.memory = "1024"
            v.customize ["modifyvm", :id, "--vram", "128"]
        end
        d.vm.provision :ansible_local do |v|
            v.playbook = "playbook.yml"
            v.inventory_path = 'inventory'
            v.limit = 'all'
        end
    end
end
