---
- hosts: all
  name: Simple nginx example Vagrant Ansible Local
  become: yes

  tasks:
    - name: Install nginx
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'nginx', 'mc' ]

    - name: Set timezone to Asia/Tokyo
      timezone:
        name: Europe/Kiev

    - name: Insert Index Page
      template:
        src: index.html
        dest: /var/www/html/index.html

    - name: Start NGiNX
      service:
        name: nginx
        state: started

    - name: Deploy SSH Key
      authorized_key: user=vagrant key="{{ lookup('file', '/vagrant/pd-master-1.pub') }}" state=present