# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "pd-master" do |d|
        d.vm.box = "ubuntu/bionic64"
        d.vm.provision :shell, path: "database_provision.sh"
        d.vm.network "public_network", ip: "192.168.0.30"
        d.vm.provider "virtualbox" do |vb|
            vb.name = "pg-master"
            vb.gui = true
            vb.memory = "1024"
        end
    end

    config.vm.define "pd-slave" do |s|
        s.vm.box = "ubuntu/bionic64"
        s.vm.provision :shell, path: "database_provision.sh"
        d.vm.network "public_network", ip: "192.168.0.31"
        s.vm.provider "virtualbox" do |vb|
            vb.name = "pg-slave"
            vb.gui = true
            vb.memory = "1024"
        end
    end
end
