# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "pd-master" do |d|
        d.vm.box = "ubuntu/bionic64"
        d.vm.network "public_network", ip: "192.168.0.30"

        d.vm.provision :shell, path: "database_provision.sh"
        d.vm.provision "shell", inline: "sudo service postgresql stop"
        d.vm.provision "file", source: "pg-master/origen/postgresql.conf", destination: "/tmp/postgresql.conf"
        d.vm.provision "file", source: "pg-master/origen/pg_hba.conf", destination: "/tmp/pg_hba.conf"
        d.vm.provision "shell", inline: "sudo cp /tmp/postgresql.conf /etc/postgresql/10/main/postgresql.conf"
        d.vm.provision "shell", inline: "sudo cp /tmp/postgresql.conf /etc/postgresql/10/main/pg_hba.conf"
        d.vm.provision "shell", inline: "sudo service postgresql start"
        d.vm.provision :shell, path: "database_create_users.sh"

        d.vm.provider "virtualbox" do |v|
            v.name = "pg-master"
            v.gui = true
            v.memory = "1024"
            v.customize ["modifyvm", :id, "--vram", "128"]
        end
    end

    config.vm.define "pd-slave" do |d|
        d.vm.box = "ubuntu/bionic64"
        d.vm.provision :shell, path: "database_provision.sh"
        d.vm.network "public_network", ip: "192.168.0.31"
        d.vm.provider "virtualbox" do |v|
            v.name = "pg-slave"
            v.gui = true
            v.memory = "1024"
            v.customize ["modifyvm", :id, "--vram", "128"]
        end
    end
end
