---
#- name: Create the hosts file for all machines.
#  lineinfile: dest=/etc/hosts line="{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
#  with_items: groups['elasticsearch']
#  tags:
#    - install

- include: yum.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install

- include: apt.yml
  when: ansible_os_family == 'Debian'
  tags:
    - install

- name: Create the Kibana directories
  file: path={{ item }} owner=kibana group=kibana state=directory
  with_items:
    - "{{ kibana_logs_dir }}"
  tags:
    - install

- name: Initial Kibana configuration.
  lineinfile: >
    dest=/opt/kibana/config/kibana.yml
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^#?\s*server\.host', line: "server.host: {{ kibana_bind_host }}" }
    - { regexp: '^#?\s*elasticsearch\.url', line: "elasticsearch.url: http://localhost:9200" }
    - { regexp: '^#?\s*logging\.dest', line: "logging.dest: {{ kibana_log_file }}" }
  notify: restart kibana
  tags:
    - install
