# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "docker-1" do |d|
        # Ubuntu 20.04.3 LTS - Focal Fossa
        # Ubuntu 18.04.6 LTS - Bionic Beaver
        # Ubuntu 16.04.7 LTS - Xenial Xerus
        # Ubuntu 14.04.6 LTS - Trusty Tahr
        d.vm.box = "ubuntu/focal64"
        d.vm.provision :shell, path: "docker_provision.sh"
        d.vm.provider "virtualbox" do |vb|
            vb.name = "docker-1"
            vb.gui = true
            vb.memory = "4048"
        end
    end
end