# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "docker-ftp-1" do |d|
        # Ubuntu 20.04.3 LTS - Focal Fossa
        d.vm.box = "ubuntu/focal64"
        d.vm.network "forwarded_port", guest: 21, host: 21

        for i in 21000..21010
            config.vm.network :forwarded_port, guest: i, host: i
        end

        d.vm.provider "virtualbox" do |vb|
            vb.name = "docker-ftp-1"
            vb.memory = "4048"
        end

        d.vm.provision "shell", path: "root-login-enable.sh"

        d.vm.provision :docker do |dc|
            dc.build_image "/vagrant", args: "-t my-name/my-new-image"
            dc.run "my-name/my-new-image", args: "-p 21:21 -p 21000-21010:21000-21010"
        end
    end
end