---
- hosts: all
  name: Dev Kafka Vagrant Ansible Local
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Install packages
      apt:
        name: ['mc']
        update_cache: yes
        state: latest
        force_apt_get: yes
