@startuml
'https://plantuml.com/deployment-diagram

'left to right direction

rectangle r <<daily>> {
    collections dailyScheduleA
    collections dailyScheduleB
}
dailyScheduleA -up[hidden]-> dailyScheduleB

rectangle p {
process primaryDerivationA
process primaryDerivationB
}

primaryDerivationA -up[hidden]-> primaryDerivationB
dailyScheduleA -> primaryDerivationA
dailyScheduleB -> primaryDerivationB

'process derivationB
process derivationC
process derivationD
process derivationE

primaryDerivationA -> derivationC
primaryDerivationB -> derivationC

derivationC -> derivationD
derivationD -> derivationE

@enduml