# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "docker-engine-1" do |d|
        # Ubuntu 20.04.3 LTS - Focal Fossa
        d.vm.box = "ubuntu/focal64"

        d.vm.provider "virtualbox" do |vb|
            vb.name = "docker-engine-1"
            vb.memory = "4048"
        end

        d.vm.provision "shell", path: "root-login-enable.sh"

        # Install Docker Engine
        d.vm.provision :docker

        # Install Docker Compose
        # First, install required plugin https://github.com/leighmcculloch/vagrant-docker-compose:
        # vagrant plugin install vagrant-docker-compose
        config.vm.provision :docker_compose
    end
end