'https://plantuml.com/sequence-diagram

@startuml

title __Simple__ **communication** example

actor Application <<My class>>
participant SpringApplication << Spring boot>>
participant RestartApplicationListener << Entry point >>
participant Restarter
participant RestartLauncher << Thread >>
participant LeakSafeThread << Thread >>

== Run an application with a RestartClassLoader ==

Application -> SpringApplication
SpringApplication -> RestartApplicationListener : ApplicationStartingEvent
RestartApplicationListener -> Restarter ** : initialize
Restarter -> LeakSafeThread ** :
Restarter -> LeakSafeThread : callAndWait
LeakSafeThread -> Restarter : start
Restarter -> RestartClassLoader ** : create
Restarter -> RestartLauncher ** : create
Restarter -> RestartLauncher :  set class loader
Restarter -> RestartLauncher :  start
Restarter -> RestartLauncher :  join
RestartLauncher -> Application : main

@enduml

@startuml

== Watch file change ==

'SpringApplication -> FileSystemWatcher **
'SpringApplication -> ClassPathFileSystemWatcher **
'SpringApplication -> RestartingClassPathChangeChangedEventListener **
'RestartingClassPathChangeChangedEventListener -> FileWatchingFailureHandler **
FileSystemWatcher -> Watcher **
FileSystemWatcher -> Thread ** : watcher
FileSystemWatcher -> Thread : start


'RestartingClassPathChangeChangedEventListener -> Restarter : restart
'ClassPathFileSystemWatcher -> FileSystemWatcher
'FileSystemWatcher -> Watcher: start new thread

@enduml


