version: '2'

services:
  cli:
    image: influxdb:2.7.5
    container_name: cli-demo
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: immerfroehlich
      DOCKER_INFLUXDB_INIT_PASSWORD: immerfroehlich
      DOCKER_INFLUXDB_INIT_ORG: TestOrg
      DOCKER_INFLUXDB_INIT_BUCKET: myFirstBucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 5dskc69ENfbtnF_g99CZgI4yDxTrZK45WbDSeY1kuz82uJFclYeEmnHyJxYRUcXVVB4O48rkn9e6p7g525wevQ==