---
#- hosts: all
#  sudo: yes
#  vars:
#    public_key: ~/.ssh/id_rsa.pub
#  tasks:
#    - name: Add ssh key
#      authorized_key: user=vagrant key="{{ lookup('file', public_key) }}"

- import_playbook: elk.yml
- import_playbook: filebeat.yml
