# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "m1" do |d|
        d.vm.box = "ubuntu/focal64"
        d.vm.hostname = "m1.szolotukhin.in.ua"
        d.vm.network :public_network, ip: "192.168.0.40"
        d.vm.provider "virtualbox" do |v|
            v.name = "ansible control node"
            v.gui = true
            v.memory = "1024"
            v.customize ["modifyvm", :id, "--vram", "128"]
        end
=begin
        d.vm.provision :ansible_local do |v|
            v.playbook = "playbook.yml"
            v.inventory_path = 'inventory'
            v.limit = 'all'
        end
=end
    end

    config.vm.define "s1" do |s|
        s.vm.box = "ubuntu/focal64"
        s.vm.hostname = "s1.szolotukhin.in.ua"
        s.vm.network :public_network, ip: "192.168.0.41"
        s.vm.provider "virtualbox" do |v|
            v.name = "ansible managed node 1"
            v.gui = true
            v.memory = "1024"
            v.customize ["modifyvm", :id, "--vram", "128"]
        end
    end
end

