@startuml
'https://plantuml.com/deployment-diagram

node JenkinsMaster
node JenkinsSlave
node GitRepository
storage GitRepositoryStorage
storage GitReferenceRepository
node DockerRegistry
storage DockerRegistryVolume
node GradleBuildCacheNode
storage GradleBuildCacheStore
node GradleDaemon
storage GradleDependencyCache

JenkinsMaster --> JenkinsSlave
JenkinsSlave --> GitReferenceRepository
JenkinsSlave --> GitRepository
JenkinsSlave --> GradleDaemon
GitRepository --> GitRepositoryStorage
GradleDaemon --> DockerRegistry
DockerRegistry --> DockerRegistryVolume
GradleDaemon --> GradleBuildCacheNode
GradleBuildCacheNode --> GradleBuildCacheStore
GradleDaemon --> GradleDependencyCache

@enduml