# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = [
    [   "192.168.0.40", "m1"    ],
    [   "192.168.0.41", "s1"    ]
]

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
#  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
#  config.ssh.private_key_path = File.expand_path('~/.vagrant.d/insecure_private_key')

  hosts.each do |h|
    hostname = h[0]
    ip = h[0]

    config.vm.define hostname do |d|
      d.vm.hostname = "%s.szolotukhin.in.ua" % hostname
      d.vm.network :public_network, ip: ip
      d.vm.provider "virtualbox" do |v|
          v.name = hostname
          v.gui = true
          v.memory = "1024"
          v.customize ["modifyvm", :id, "--vram", "128"]
      end
    end
  end
end

