NAME = "oracle-database-dev-01"

Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/7"
  config.vm.box_url = "https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json"
  config.vm.define NAME

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.name = NAME
    v.gui = true
  end

  config.vm.hostname = NAME

  config.vm.network "forwarded_port", guest: 1521, host: 1522
end