@startuml
'https://plantuml.com/activity-diagram-beta

start


'process
if (source is collection) then (yes)
    'processCollection
    while (has more elements?)
        'processObjectFromCollection
        :processObject;
        'processObject
    endwhile
else (no)
    'processObject

    'pre-processable properties
    while (has more property?)
        if (is pre-processable property?) then (yes)
            :processProperty;
            'get property value
            'processObject or processCollection

            if (is required replace value?) then (yes)
                :replace references;
            else (no)
            endif
        else (no)
        endif
    endwhile

    'process object itself
    if (is processable property?) then (yes)
        'doProcessObject
        :doProcessObject;
    else (no)
    endif


    'post-processable properties
    while (has more property?)
        if (is post-processable property?) then (yes)
            :processProperty;
            'get property value
            'processObject or processCollection
        else (no)
        endif
    endwhile

endif



stop

@enduml
