@startuml
'https://plantuml.com/component-diagram


actor DerivationExecutor
[DerivationMonitor]
[Scheduler]
[RunnerExecutor]
[StatusResolver]
[DeferredPersister]
queue EventBus
database Database

DerivationExecutor --> [DerivationMonitor]

[DerivationMonitor] --> [Scheduler]
[Scheduler] --> [RunnerExecutor]
[RunnerExecutor] --> [StatusResolver]
[StatusResolver] --> [DeferredPersister]
[StatusResolver] --> [EventBus]
[DeferredPersister] --> [Database]
[DerivationMonitor] --> EventBus


@enduml