SELECT tablespace_name, file_name FROM dba_data_files;

ALTER TABLESPACE GE_TABLESPACE_DEV01 ADD DATAFILE '<path>' SIZE 1G AUTOEXTEND ON NEXT 500M MAXSIZE 30G;
create user GE_DEV01 identified by "GE_DEV01";
GRANT CREATE SESSION TO GE_DEV01;
GRANT CREATE TABLE TO GE_DEV01;
GRANT CREATE SEQUENCE TO GE_DEV01;