#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2018 Oracle and/or its affiliates. All rights reserved.
#
# Since: January, 2018
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle database Vagrant virtual machine.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#

# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://github.com/oracle/vagrant-boxes/tree/master/OracleDatabase/12.1.0.2

VAGRANTFILE_API_VERSION = "2"

BOX_URL = "https://oracle.github.io/vagrant-boxes/boxes"
BOX_NAME = "oraclelinux/7"

NAME = "oracle-12102-vagrant"

SYSTEM_TIMEZONE = 'UTC'

LISTENER_PORT = 1521
EM_EXPRESS_PORT = 5500

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
  config.vm.define NAME

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.name = NAME
    v.gui = true
  end

  config.vm.hostname = NAME

  config.vm.network "forwarded_port", guest: LISTENER_PORT, host: LISTENER_PORT
  config.vm.network "forwarded_port", guest: EM_EXPRESS_PORT, host: EM_EXPRESS_PORT

  config.vm.provision "shell", path: "scripts/install.sh", env:
    {
       "ORACLE_BASE"         => "/opt/oracle",
       "ORACLE_HOME"         => "/opt/oracle/product/12.1.0.2/dbhome_1",
       "ORACLE_SID"          => "ORCLCDB",
       "ORACLE_PDB"          => "ORCLPDB1",
       "ORACLE_CHARACTERSET" => "AL32UTF8",
       "ORACLE_EDITION"      => "EE",
       "LISTENER_PORT"       => LISTENER_PORT,
       "EM_EXPRESS_PORT"     => EM_EXPRESS_PORT,
       "SYSTEM_TIMEZONE"     => SYSTEM_TIMEZONE
    }

end